global:
  smtp_smarthost: mailhog:1025
  smtp_from: alertmanager@demo.local
  smtp_require_tls: false
route:
  receiver: mail
  group_wait: 5s
  repeat_interval: 1h
receivers:
  - name: mail
    email_configs: [{ to: ops@demo.local, send_resolved: true }]
