name: demo-prom
services:
  prometheus:
    image: docker.io/prom/prometheus:v2.53.0
    ports: ["9090:9090"]
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml:ro"]
  node-exporter:
    image: docker.io/prom/node-exporter:v1.8.2
    ports: ["9100:9100"]
